### ISSUE TITLE
Conda environment(s)

### ISSUE THREAD

**Issue by evaegelyng** [wpearman1996/MARES_database_pipeline#1]
It would be very useful if you added a conda environment description (.yml file) for the environment(s) you used for the pipeline :-) Then users could import the environment and just update packages where necessary.

**Comment by evaegelyng** [comment]
Hi William,

Yes, I managed to install everything and to make my own database following your pipeline :-) But you're right, the perl modules were the most tricky, and couldn't be installed with conda. I still think it would be helpful with a conda environment description though, but even better if you can also provide some instructions for the perl modules!

**Comment by wpearman1996** [comment]
Thanks Eva! I've provided some instructions on the readme file on how to install the dependencies, currently it's focused on the perl modules and briefly covers some of the python dependencies. These commands are what worked for me a on fresh install of Ubuntu 20.04, so they may not work on other operating systems.

I'm also in the process of updating the genbank_to_fasta.py script to remove the reliance on python2. 

I will hopefully be able to provide a more substantial set of instructions in the near future.

I'll close this issue now, but feel free to re-open it if need be.
